ENABLE:
  - PYTHON
  - YAML
ENABLE_LINTERS:  # Explicitly list all desired linters
  - PYTHON_PYLINT
  - PYTHON_FLAKE8
  - PYTHON_PYDOCSTYLE
  - PYTHON_BLACK
  - PYTHON_ISORT
  - PYTHON_BANDIT
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - PYTHON_RUFF
PYDOCSTYLE_CONFIG: ".pydocstyle.ini"  # Optional: custom config
ADDITIONAL_PYDOCSTYLE_ARGS: "--convention=google"
DISABLE_LINTERS:
  - YAML_V8R
SARIF_REPORTER: true
