ENABLE:
  - PYTHON
  - YAML
PYTHON_PYDOCSTYLE: true  # Explicitly add this
VALIDATE_PYTHON: true
VALIDATE_PYTHON_PYLINT: true
VALIDATE_PYTHON_FLAKE8: true
VALIDATE_PYTHON_DOCSTRINGS: true
ADDITIONAL_PYDOCSTYLE_ARGS: "--convention=google"

DISABLE_LINTERS:
  - YAML_V8R

GITHUB_STATUS_REPORTER: true

JSON_JSONLINT_ARGUMENTS: ["--comments"]

JSON_PRETTIER_ARGUMENTS: ["--trailing-comma", "none"]

SARIF_REPORTER: true
