ENABLE:
  - BASH
  - DOCKERFILE
  - EDITORCONFIG
  - JSON
  - MARKDOWN
  - YAML

ENABLE_LINTERS:
  - PYTHON_RUFF

DISABLE_LINTERS:
  - YAML_V8R

JSON_JSONLINT_ARGUMENTS: ["--comments"]

JSON_PRETTIER_ARGUMENTS: ["--trailing-comma", "none"]

PYTHON_RUFF_PRE_COMMANDS:
  # Update ruff
  - command: "pip install --upgrade ruff"
    continue_if_failed: false
  - command: "wget -O .github/linters/pyproject.toml https://raw.githubusercontent.com/home-assistant/core/refs/heads/dev/pyproject.toml"
    continue_if_failed: false

SARIF_REPORTER: true
