ENABLE:
  - BASH
  - DOCKERFILE
  - EDITORCONFIG
  - JSON
  - MARKDOWN
  - YAML
  
ENABLE_LINTERS:
  - PYTHON_RUFF

DISABLE_LINTERS:
  - YAML_V8R

JSON_JSONLINT_ARGUMENTS: ["--comments"]

JSON_PRETTIER_ARGUMENTS: ["--trailing-comma", "none"]

MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: ".megalinter/.markdown-link-check.json"

PYTHON_RUFF_PRE_COMMANDS:
  - command: 'wget -O pyproject.toml https://raw.githubusercontent.com/home-assistant/core/refs/heads/dev/pyproject.toml'
    continue_if_failed: false

SARIF_REPORTER: true

