"""Constants for the Eaton xComfort Bridge integration."""

DOMAIN = "xcomfort_bridge"
CONF_MAC = "mac_address"
CONF_AUTH_KEY = "auth_key"
CONF_IDENTIFIER = "identifier"
CONF_DIMMING = "dimming"
CONF_GATEWAYS = "gateways"
CONF_TEST_OPTION_1 = "test_option_1"
CONF_TEST_OPTION_2 = "test_option_2"
CONF_TEST_SECTION = "test_section"
CONF_TEST_OPTION_3 = "test_option_3"
CONF_TEST_OPTION_4 = "test_option_4"
