"""Constants for the Eaton xComfort Bridge integration."""

DOMAIN = "xcomfort_bridge"
CONF_MAC = "mac_address"
CONF_AUTH_KEY = "auth_key"
CONF_IDENTIFIER = "identifier"
CONF_DIMMING = "dimming"
CONF_GATEWAYS = "gateways"
CONF_POWER_ENERGY_SECTION = "power_energy_sensors"
CONF_ADD_ROOM_POWER_SENSORS = "add_room_power_sensors"
CONF_ADD_HEATER_POWER_SENSORS = "add_heater_power_sensors"
CONF_ADD_LIGHT_POWER_SENSORS = "add_light_power_sensors"
