---
# MegaLinter GitHub Action configuration file
# More info at https://oxsecurity.github.io/megalinter
name: RuffLinter

on:
  push:
  pull_request:
    branches: [main,develop,megalinter]

jobs:
  build:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./custom_components/xcomfort_bridge"
